/* double include preventer */
#ifndef _MSG_H
#define _MSG_H

/* file: msg.h, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: C:\Users\DMARJA~1\AppData\Local\Temp\Cfg_Gen-1632938181978-3\OsProxyFiles-1632939743589-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Wed Sep 29 20:22:27 2021 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif


#endif   /* double include preventer */

/* END OF C:\work\AUTOSAR\CanCollege\Autosar4\_AFS_Combined\Appl\GenDataVtt\msg.h */

